name: 'vsix'

on:
  push:
  pull_request:
  schedule:
    - cron: '0 15 * * 3'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build VSIX package
      run: |
        cd vscode-client
        sudo yarn global add vsce
        sudo chown -R $USER:$(id -gn $USER) $HOME/.config
        yarn
        vsce package
    - uses: actions/upload-artifact@master
      with:
        name: vhdl-lsp-vsix
        path: vscode-client/vhdl-lsp-*.vsix
    - if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
      run: |
        curl -X POST https://api.github.com/repos/ghdl/docker/dispatches \
        -H "Content-Type: application/json" \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -H "Authorization: token ${{ secrets.GHDL_BOT }}" \
        --data '{"event_type": "ext"}'